name: "XQZmeSIR"
picture: "assets/img/picture.jpg"
bio: "just a guy who's on his way to become a python developer"
meta:
  lang: "en"
  description: "just a guy who's on his way to become a python developer"
  title: "XQZmeSIR"
  author: "XQZmeSIR"
  siteUrl: "https://xqzmesir.github.io/taplink/"
links:
  - name: "Github"
    url: "https://github.com/xqzmesir"
  - name: "Telegram"
    url: "https://t.me/xqzmesir"
  - name: "Digital Garden"
    url: "https://xqzmesir.ru/"
  - name: "X (Twitter)"
    url: "https://x.com/XQZmeSIR"
  - name: "Email"
    url: "mailto:xqzmesir@inbox.ru"
theme: "custom"